services:
  app:
    build: .
    container_name: posts-app
    ports:
      - 3002:3000
    environment:
      - ENVIRONMENT=production
      - DB_HOST=mysql
      - DB_DATABASE=posts
      - DB_USER=root
      - DB_PASSWORD=password
    command: npm start
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: posts-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password